version: '2'
services:
  jira:
    image: registry.cn-hangzhou.aliyuncs.com/c3t3m3/docker-jira:aliyun
    ports:
      - "8080:8080"
    links:
      - jira-mysql
    networks:
      - jira-net
  jira-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/c3t3m3/docker-mysql:aliyun
    networks:
      - jira-net
networks:
  jira-net:
    driver: bridge
